---
title: "Data Manipulation"
output: github_document
---
```{r}
library(tidyverse)
```
```{r}
litters_df=read.csv("data/FAS_litters.csv")
litters_df=janitor::clean_names(litters_df)
pups_df=read.csv("data/FAS_pups.csv")
pups_df=janitor::clean_names(pups_df)
```
##'select'
'select' is used to select columns
```{r}
select(litters_df,litter_number, gd0_weight,pups_dead_birth)
select(litters_df,gd0_weight,group)
select(litters_df,litter_number, gd0_weight:gd_of_birth)
select(litters_df,litter_number,starts_with("pups"))
select(litters_df,-litter_number)
select(litters_df,-starts_with("gd"))
select(litters_df,group,litter_id=litter_number)
select(litters_df,group,litter_id=litter_number,everything())
```
'select' vs 'pull'
```{r}
select(litters_df,group)
pull(litters_df,group)
```
```{r}
rename(litters_df,litters_id=litter_number)
relocate(litters_df,litter_number)
```
```{r}
select(pups_df,litter_number,sex,pd_ears)
```
##'filter'
get rid of rows using 'filter'
```{r}
filter(litters_df,group=='Mod8')
filter(litters_df,group!='Mod8')
filter(litters_df,gd0_weight>=20)
filter(litters_df,group=='Mod8'|group=='Mod7')
filter(litters_df,group%in%c('Con7','Con8'))
filter(litters_df,!(group=='Con7'))
filter(litters_df,gd0_weight>=20,group%in%c('Con7','Con8'))
```
what about missing rows
```{r}
drop_na(litters_df)
drop_na(litters_df,gd0_weight)
```
##'mutate'
```{r}
mutate(litters_df,wt_gain= gd18_weight-gd0_weight)
mutate(litters_df,str_to_lower(group))
mutate(litters_df,
       wt_gain= gd18_weight-gd0_weight,
       str_to_lower(group)
       )
```
##'arrange'
```{r}
arrange(litters_df,gd0_weight)
arrange(litters_df,group,gd0_weight)
```

