---
title: "Tidy Data"
output: github_document
---
```{r}
library(tidyverse)
```
## PULSE data

```{r}
pulse_df=
  haven::read_sas("data/public_pulse_data.sas7bdat")|>
  janitor::clean_names()|>
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    values_to = "bdi_score",
    names_prefix = "bdi_score_"
  )|>
  mutate(
    replace(visit,visit=="bl","00m")
  )
```
```{r}
litter_df=
  read_csv("data/FAS_litters.csv")|>
  janitor::clean_names()|>
  select(litter_number,gd0_weight,gd18_weight)|>
  pivot_longer(
    gd0_weight:gd18_weight,
    names_to = "gd",
    values_to = "weight",
    names_prefix= "gd"
  )|>
  mutate(
  gd=case_match(gd, 
  "0_weight" ~ 0,
  "18_weight"~ 18,
  ))
```
##LoTR
Import LoTR words data
```{r}
fellowship_df=
  readxl::read_excel("data/LotR_Words.xlsx", range ="B3:D6")|>
  mutate(movie="fellowship")
tower_df=
  readxl::read_excel("data/LotR_Words.xlsx", range ="F3:H6")|>
  mutate(movie="two_towers")
return_df=
  readxl::read_excel("data/LotR_Words.xlsx", range ="J3:L6")|>
  mutate(movie="return_of_king")

lotr_df=
  bind_rows(fellowship_df,tower_df,return_df)|>
  janitor::clean_names()|>
  pivot_longer(
    male:female,
    names_to = "gender",
    values_to= "Words"
  )|>
  relocate(movie)
```
## Revisit FAS
```{r}
litter_df=
  read_csv("data/FAS_litters.csv")|>
  janitor::clean_names()|>
  mutate(wt_gain=gd18_weight-gd0_weight)|>
  select(litter_number, group, wt_gain)|>
  separate(group,into=c("dose","days_of_tx"), 3)
```
```{r}
pups_df=
  read_csv("data/FAS_pups.csv")|>
  janitor::clean_names()|>
  mutate(
    sex=case_match(
      sex,
      1 ~ "male",
      2 ~ "female"
        ))

fas_df=
  left_join(pups_df,litter_df, by="litter_number")
```

  